# Generated by Django 4.0 on 2021-12-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_age_alter_customuser_sex_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_email',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
