# Generated by Django 4.0 on 2021-12-27 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True)),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=100, null=True)),
                ('countrty', models.CharField(max_length=100, null=True)),
                ('actor', models.CharField(max_length=255, null=True)),
                ('director', models.CharField(max_length=255, null=True)),
                ('runtime', models.CharField(max_length=100, null=True)),
                ('overview', models.TextField(blank=True)),
                ('img_path', models.CharField(max_length=255, null=True)),
                ('release_date', models.CharField(max_length=100, null=True)),
                ('vote_count', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
    ]
