# Generated by Django 4.0 on 2021-12-28 07:12


import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True)),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('actor', models.CharField(blank=True, max_length=255)),
                ('director', models.CharField(blank=True, max_length=255)),
                ('runtime', models.CharField(blank=True, max_length=100)),
                ('overview', models.TextField(blank=True)),
                ('image_path', models.CharField(blank=True, max_length=255)),
                ('release', models.CharField(blank=True, max_length=100)),
                ('vote_count', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('movie_rating', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('ott', models.CharField(blank=True, max_length=100)),
            ],
        ),
<<<<<<< HEAD
        migrations.CreateModel(
            name='MovieReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True)),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entertainment.movies')),
            ],
        ),
=======
>>>>>>> 049ccbd629448ea6889cb78d82269a9ac2bdc5d2
    ]
