# Generated by Django 4.0 on 2022-01-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0004_alter_contents_actor_alter_contents_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='content_rating',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='contents',
            name='country',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='contents',
            name='genre',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='contents',
            name='ott',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='contents',
            name='release',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='contents',
            name='runtime',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='contents',
            name='type',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
