# Generated by Django 4.0 on 2022-01-05 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0005_alter_contents_content_rating_alter_contents_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cost', models.IntegerField()),
                ('pixel', models.CharField(max_length=30)),
                ('max_user_count', models.IntegerField()),
            ],
        ),
    ]
