# Generated by Django 4.0 on 2022-01-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0006_ott'),
    ]

    operations = [
        migrations.AddField(
            model_name='ott',
            name='img_path',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
