# Generated by Django 4.0 on 2022-01-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0007_ott_img_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
