# Generated by Django 4.0 on 2022-01-08 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0008_contents_tmdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='keywords',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contents',
            name='actor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contents',
            name='content_rating',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='contents',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contents',
            name='director',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contents',
            name='genre',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='contents',
            name='image_path',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contents',
            name='kor_image_path',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contents',
            name='kor_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contents',
            name='ott',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contents',
            name='release',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contents',
            name='runtime',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contents',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contents',
            name='type',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
