# Generated by Django 4.0 on 2022-01-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0009_contents_keywords_alter_contents_actor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='actor',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='contents',
            name='country',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contents',
            name='director',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='contents',
            name='ott',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='contents',
            name='release',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='contents',
            name='runtime',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
