# Generated by Django 4.0 on 2022-01-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0011_alter_contents_country_alter_contents_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='actor',
            field=models.CharField(blank=True, max_length=700),
        ),
        migrations.AlterField(
            model_name='contents',
            name='country',
            field=models.CharField(blank=True, max_length=700),
        ),
        migrations.AlterField(
            model_name='contents',
            name='director',
            field=models.CharField(blank=True, max_length=700),
        ),
        migrations.AlterField(
            model_name='contents',
            name='keywords',
            field=models.CharField(blank=True, max_length=700),
        ),
        migrations.AlterField(
            model_name='contents',
            name='kor_title',
            field=models.CharField(blank=True, max_length=700),
        ),
    ]
