# Generated by Django 4.0 on 2022-01-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0013_alter_contents_keywords_alter_contents_kor_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='actor',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='contents',
            name='country',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='contents',
            name='director',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
