# Generated by Django 4.0 on 2022-01-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0015_alter_contents_actor_alter_contents_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='genre',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
