# Generated by Django 4.0 on 2022-01-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entertainment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OTTservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, default=0)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('member_number', models.IntegerField(blank=True, default=1)),
                ('member_child_count', models.IntegerField(blank=True, default=1)),
                ('member_adult_count', models.IntegerField(blank=True, default=1)),
                ('price_range', models.IntegerField(blank=True, default=0)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('pixel', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first', models.CharField(blank=True, max_length=50)),
                ('second', models.CharField(blank=True, max_length=50)),
                ('third', models.CharField(blank=True, max_length=50)),
                ('tmdb_id', models.CharField(blank=True, max_length=50)),
                ('prefer_contents', models.ManyToManyField(to='entertainment.Contents')),
            ],
        ),
    ]
