# Generated by Django 4.0 on 2022-01-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0005_alter_contents_content_rating_alter_contents_country_and_more'),
        ('service', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ottservice',
            name='member_adult_count',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='ottservice',
            name='member_child_count',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='ottservice',
            name='member_teenager_count',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='ottservice',
            name='pixel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ottservice',
            name='prefer_movie',
            field=models.ManyToManyField(blank=True, to='entertainment.Contents'),
        ),
    ]
