# Generated by Django 4.0 on 2022-01-02 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('service', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ottservice',
            name='age',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ottservice',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='ottservice',
            name='genre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ottservice',
            name='member_number',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='ottservice',
            name='price_range',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ottservice',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customuser'),
        ),
    ]
