# Generated by Django 4.0 on 2022-01-04 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_ottservice_member_adult_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ottservice',
            old_name='prefer_movie',
            new_name='prefer_contents',
        ),
    ]
