# Generated by Django 4.0 on 2022-01-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0005_alter_contents_content_rating_alter_contents_country_and_more'),
        ('service', '0004_rename_prefer_movie_ottservice_prefer_contents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ottservice',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='ottservice',
            name='prefer_contents',
            field=models.ManyToManyField(to='entertainment.Contents'),
        ),
    ]
