# Generated by Django 4.0 on 2022-01-04 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0005_alter_contents_content_rating_alter_contents_country_and_more'),
        ('service', '0005_rename_user_id_ottservice_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ottservice',
            name='prefer_contents',
        ),
        migrations.AddField(
            model_name='ottservice',
            name='prefer_contents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entertainment.contents'),
        ),
    ]
