# Generated by Django 4.0 on 2022-01-05 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_alter_ottservice_prefer_contents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ottservice',
            old_name='user',
            new_name='user_id',
        ),
    ]
