# Generated by Django 4.0 on 2022-01-05 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_rename_user_ottservice_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ottservice',
            name='prefer_contents',
        ),
    ]
