# Generated by Django 4.0 on 2022-01-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0007_ott_img_path'),
        ('service', '0010_remove_ottservice_prefer_contents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ottservice',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='ottservice',
            name='prefer_contents',
            field=models.ManyToManyField(to='entertainment.Contents'),
        ),
    ]
