# Generated by Django 4.0 on 2022-01-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_rename_user_id_ottservice_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ottservice',
            name='first',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ottservice',
            name='second',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ottservice',
            name='third',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
