# Generated by Django 4.0 on 2022-01-06 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_ottservice_first_ottservice_second_ottservice_third'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ottservice',
            name='member_teenager_count',
        ),
    ]
