# Generated by Django 4.0 on 2022-01-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_remove_ottservice_member_teenager_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='ottservice',
            name='tmdb_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
