# Generated by Django 4.0 on 2022-01-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_ottservice_tmdb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ottservice',
            name='tmdb_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
