# Generated by Django 4.0 on 2022-01-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_contentrecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentrecommendation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
