# Generated by Django 4.0 on 2022-01-07 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0008_contents_tmdb_id'),
        ('service', '0017_contentrecommendation_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentrecommendation',
            name='recommend_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entertainment.contents'),
        ),
    ]
