# Generated by Django 4.0 on 2022-01-06 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('entertainment', '0007_ott_img_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTTRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_ott', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entertainment.ott')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='ContentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entertainment.ott')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
            ],
        ),
    ]
