# Generated by Django 4.0 on 2022-01-06 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ottrecommendation',
            name='recommended_ott',
        ),
        migrations.RemoveField(
            model_name='ottrecommendation',
            name='user',
        ),
        migrations.DeleteModel(
            name='ContentRecommendation',
        ),
        migrations.DeleteModel(
            name='OTTRecommendation',
        ),
    ]
