# Generated by Django 4.0 on 2022-01-07 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('entertainment', '0008_contents_tmdb_id'),
        ('mypage', '0002_remove_ottrecommendation_recommended_ott_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyOTT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OTT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entertainment.ott')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='MyContents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.ManyToManyField(to='entertainment.Contents')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
            ],
        ),
    ]
