# Generated by Django 4.0 on 2022-01-07 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0004_mycontents_created_at_myott_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myott',
            old_name='OTT',
            new_name='ott',
        ),
    ]
