# Generated by Django 4.0 on 2022-01-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0008_contents_tmdb_id'),
        ('mypage', '0005_rename_ott_myott_ott'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myott',
            name='ott',
        ),
        migrations.AddField(
            model_name='myott',
            name='ott',
            field=models.ManyToManyField(to='entertainment.OTT'),
        ),
    ]
