# Generated by Django 4.0 on 2022-01-07 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0008_contents_tmdb_id'),
        ('mypage', '0006_remove_myott_ott_myott_ott'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycontents',
            name='contents',
        ),
        migrations.AddField(
            model_name='mycontents',
            name='contents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entertainment.contents'),
        ),
        migrations.RemoveField(
            model_name='myott',
            name='ott',
        ),
        migrations.AddField(
            model_name='myott',
            name='ott',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entertainment.ott'),
        ),
    ]
